# Generated by Django 5.2 on 2025-05-02 16:34

import django_cryptography.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=django_cryptography.fields.encrypt(
                phonenumber_field.modelfields.PhoneNumberField(
                    blank=True,
                    help_text="International format: +123456789",
                    max_length=128,
                    null=True,
                    region=None,
                    verbose_name="phone number",
                )
            ),
        ),
    ]
